run_name: 'invaders-ppo-ps-final-3'
seed: 42
checkpoint_interval: 50

sverl:
  type: Shapley
  model: StandardAtari
  target: actor
  state_sampler: ProceduralSampler
  agent_checkpoint: models/invaders/ppo.pt
  characteristic_checkpoint: checkpoints/invaders-ppo-pc-final-3/400.pt