run_name: 'breakout-ppo-ps-1L'
seed: 42
checkpoint_interval: 50

sverl:
  type: Shapley
  model: LargeAtari
  target: actor
  state_sampler: ProceduralSampler
  agent_checkpoint: models/breakout/ppo.pt
  characteristic_checkpoint: checkpoints/breakout-ppo-pc-1LL-1744690067/400.pt
