run_name: 'breakout-ppo-vc-1'
seed: 42
checkpoint_interval: 50

sverl:
  type: Characteristic
  model: StandardAtari
  target: critic
  state_sampler: ProceduralSampler
  agent_checkpoint: models/breakout/ppo.pt
  masker: ZeroMasker
