run_name: "grid"
seed: 42
checkpoint_interval: 1000000
track_wandb: false

agent:
  type: QLearning
  actor: SimpleActor
  critic: SimpleCritic
  total_timesteps: 1000000
  alpha: 0.2
  gamma: 1
  epsilon: 0.2

  environment:
    type: Simple
    name: Grid-v0
    num_envs: 1
