run_name: 'grid-ps'
seed: 42
checkpoint_interval: 20

sverl:
  type: Shapley
  model: StandardSimple
  target: actor
  state_sampler: ProceduralSampler
  agent_checkpoint: models/testing/mastermind.pt
  characteristic_checkpoint: checkpoints/mastermind-pc/200.pt