run_name: 'pong-ppo-vs-final-2'
seed: 42
checkpoint_interval: 50

sverl:
  type: Shapley
  model: StandardAtari
  target: critic
  state_sampler: ProceduralSampler
  agent_checkpoint: models/pong/ppo.pt
  characteristic_checkpoint: checkpoints/pong-ppo-vc-final-2/400.pt
