run_name: "pong-ppo"
seed: 42
checkpoint_interval: 200
track_wandb: true

agent:
  type: PPO
  actor: AtariActor
  critic: AtariCritic

  learning_rate: 0.00025
  total_timesteps: 10000000
  clip_coefficient: 0.1

  environment:
    type: Atari
    name: PongNoFrameskip-v4
    num_envs: 8
    record: True
    record_interval: 200
