run_name: 'breakout-ppg-ps-final-3'
seed: 42
checkpoint_interval: 50

sverl:
  type: Shapley
  model: StandardAtari
  target: actor
  state_sampler: ProceduralSampler
  agent_checkpoint: models/breakout/ppg.pt
  characteristic_checkpoint: checkpoints/breakout-ppg-pc-final-3/400.pt