run_name: 'breakout-ppo-pc-final-2'
seed: 42
checkpoint_interval: 50

sverl:
  type: Characteristic
  model: StandardAtari
  target: actor
  state_sampler: ProceduralSampler
  agent_checkpoint: models/breakout/ppo.pt
  masker: MeanMasker
