run_name: 'breakout-ppo-pc-1LL'
seed: 42
checkpoint_interval: 50

sverl:
  type: Characteristic
  model: LargerAtari
  target: actor
  state_sampler: ProceduralSampler
  agent_checkpoint: models/breakout/ppo.pt
  masker: ZeroMasker
