run_name: 'breakout-ppo-vs-1'
seed: 42
checkpoint_interval: 50

sverl:
  type: Shapley
  model: StandardAtari
  target: critic
  state_sampler: ProceduralSampler
  agent_checkpoint: models/breakout/ppo.pt
  characteristic_checkpoint: checkpoints/breakout-ppo-vc-5-1744643519/500.pt
