run_name: 'invaders-ppo-pc-final-2'
seed: 42
checkpoint_interval: 50

sverl:
  type: Characteristic
  model: StandardAtari
  target: actor
  state_sampler: ProceduralSampler
  agent_checkpoint: models/invaders/ppo.pt
  masker: MeanMasker
