run_name: 'invaders-ppg-vs-final-3'
seed: 42
checkpoint_interval: 50

sverl:
  type: Shapley
  model: StandardAtari
  target: critic
  state_sampler: ProceduralSampler
  agent_checkpoint: models/invaders/ppg.pt
  characteristic_checkpoint: checkpoints/invaders-ppg-vc-final-3/400.pt
