run_name: 'pong-ppg-vc-final-2'
seed: 42
checkpoint_interval: 50

sverl:
  type: Characteristic
  model: StandardAtari
  target: critic
  state_sampler: ProceduralSampler
  agent_checkpoint: models/pong/ppg.pt
  masker: MeanMasker
