run_name: 'pong-ppg-vs-final-1'
seed: 42
checkpoint_interval: 50

sverl:
  type: Shapley
  model: StandardAtari
  target: critic
  state_sampler: ProceduralSampler
  agent_checkpoint: models/pong/ppg.pt
  characteristic_checkpoint: checkpoints/pong-ppg-vc-final-1/400.pt
